@startuml

hide empty attributes
hide empty methods

package "Catalog Context" {
    class "Book" as CatalogBook {
        ISBN
        Title
        Author
    }
}

package "Lending Context" {
    class "Book" as LendingBook {
        copyId
        condition
        location
    }
}

@enduml
