%%{init: {
  'theme': 'base',
  'gitGraph': {
    'showCommitLabel': false,
    'mainBranchName': 'main',
    'rotateCommitLabel': false
  },
  'themeVariables': {
    'git0': '#ED1944',
    'git1': '#004A8D',
    'gitBranchLabel0': '#FFFFFF',
    'gitBranchLabel1': '#FFFFFF',
    'tagLabelColor': '#FFFFFF',
    'tagLabelBackground': '#ED1944',
    'tagLabelBorder': '#ED1944'
  }
}}%%
gitGraph
   commit
   commit
   branch feature
   checkout feature
   commit
   commit
   commit
   checkout main
   merge feature tag: "Deploy"
   commit
